# Generated by Django 4.2.11 on 2025-05-04 02:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo_boletin', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('regiones', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None)),
                ('etiqueta', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(max_length=200)),
                ('fuente', models.CharField(max_length=50)),
                ('image', models.ImageField(default='test.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='correos',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
