# Generated by Django 4.2.11 on 2025-05-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('recibir_correos', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('lector', 'Lector')], default='lector', max_length=10)),
            ],
        ),
    ]
