# Generated by Django 4.2.11 on 2025-04-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='correos',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
