# Generated by Django 5.1.2 on 2024-10-26 01:27

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo_boletin', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('regiones', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None)),
                ('etiqueta', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(max_length=100)),
                ('fuente', models.CharField(max_length=50)),
            ],
        ),
    ]
