# Generated by Django 5.1.2 on 2024-10-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletines',
            name='image',
            field=models.ImageField(default='test.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='boletines',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
